services:
  api:
    build:
      # context: ../..  # корень монорепо
      dockerfile: apps/api/Dockerfile
    ports:
      - "3000:3000"
    env_file: apps/api/.env

  web:
    build:
      # context: ../..
      dockerfile: apps/web/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
