services:
  api:
    image: ${ECR_REGISTRY}/queue-view/api:staging
    restart: always
    ports:
      - "3001:3000"  # другой порт чтобы не конфликтовал с prod
    env_file: .env.staging

  web:
    image: ${ECR_REGISTRY}/queue-view/web:staging
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - api
